# Alacritty Configuration

[env]
TERM = "xterm-256color"

[window]
padding = { x = 4, y = 2 }
dynamic_padding = false
decorations = "none"
opacity = 1.0

[scrolling]
history = 100000
multiplier = 3

[font]
size = 11.0

[font.normal]
style = "Regular"
#family = "Terminus (TTF)"
family = "DejaVu Sans Mono"
#family = "Consolas"
#family = "Liberation Mono"
#family = "Terminus"
#family = "Courier Prime Code"


#draw_bold_text_with_bright_colors = false
#custom_cursor_colors = true

[bell]
animation = "EaseOutExpo"
color = "0xffffff"
duration = 0


[keyboard]
bindings = [
	{ key = "Insert", mods = "Control", action = "Copy" },
	{ key = "Insert", mods = "Shift", action = "Paste" },
	{ key = "Back", mods = "Control", chars = "\u0015" },
]

[selection]
semantic_escape_chars = ",â”‚`|:\"' ()[]{}<>"
save_to_clipboard = true

#[mouse]
#double_click = { threshold = 300 }
#triple_click = { threshold = 300 }
#hide_when_typing = true

#[mouse_bindings]
#mouse = "Middle"
#action = "PasteSelection"


[mouse]
hide_when_typing = true
bindings = [
	{ mouse = "Middle", action = "PasteSelection" },
]

[cursor]
style = "Underline"
unfocused_hollow = true

#live_config_reload = true

[general]
import = [
    "~/.config/alacritty/omni.toml"
]
